final_proj/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('wpFiles/', include('wpFiles.urls')),
    path(r'^ratings/', include('star_ratings.urls', namespace='ratings')),
    path('accounts/', include('django.contrib.auth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

final_proj/mysite/wpFiles/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:dept_id>/', views.classInDept, name='classInDept'),
    path('<int:class_id>/uploads', views.uploads, name='uploads'),
    path('upload',views.uploadFile, name='uploadFile'),
    path(r"^search/", include("watson.urls", namespace="watson")),
    path('search', views.search, name='search'),
    path('signup/', views.signup.as_view(), name='signup'),
    
	
]

final_proj/mysite/documents/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
       
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text
        
      
    
        

final_proj/mysite/media/documents/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating


# Create your models here.
class Academic_dept(models.Model):
    dept_code = models.CharField(max_length=10,unique=True)
    dept_name = models.CharField(max_length=100)
    def __str__(self):
        return self.dept_code
    
class Academic_class(models.Model):
    class_code = models.CharField(max_length=5,unique=True)
    dept_code = models.ForeignKey(
        Academic_dept,
        on_delete=models.CASCADE,
    )
    class_name = models.CharField(max_length=30)
    def __str__(self):
        return self.class_code
    
class Upload(models.Model):
    alias = models.CharField(max_length=30,unique=True)
    class_code = models.ForeignKey(
        Academic_class,
        on_delete=models.CASCADE,
    )
    document = models.FileField(upload_to='documents/')
    rating = GenericRelation(Rating, related_query_name='Files')
    downloads = models.IntegerField(default=0)
    flags = models.IntegerField
    upload_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.alias 
  

final_proj/mysite/wpFiles/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating


class Academic_dept(models.Model):
    dept_code = models.CharField(max_length=10,unique=True)
    dept_name = models.CharField(max_length=100)
    def __str__(self):
        return self.dept_code
    
class Academic_class(models.Model):
    class_code = models.CharField(max_length=5,unique=True)
    dept_code = models.ForeignKey(
        Academic_dept,
        on_delete=models.CASCADE,
    )
    class_name = models.CharField(max_length=30)
    def __str__(self):
        return self.class_code
    
class Upload(models.Model):
    alias = models.CharField(max_length=30,unique=True)
    class_code = models.ForeignKey(
        Academic_class,
        on_delete=models.CASCADE,
    )
    document = models.FileField(upload_to='documents/')
    rating = GenericRelation(Rating)
    upload_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.alias 
    class Meta:
        ordering = ["-upload_date"]


    

    
  

final_proj/mysite/wpFiles/forms.py
from django import forms
from .models import Upload

class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = [
            "document",
            "alias",
            "class_code",
                      
           
        ]

final_proj/mysite/wpFiles/views.py
from django.shortcuts import render
from .models import Academic_dept, Academic_class, Upload
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from .forms import UploadForm
from .models import Upload
from watson import search as watson
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic




def index(request):
    dept_list = Academic_dept.objects.order_by('dept_code')
    context = {'dept_list': dept_list}
    return render(request, 'wpFiles/index.html', context)
          
def classInDept(request, dept_id):
    dept = get_object_or_404(Academic_dept, pk=dept_id)
    return render(request, 'wpFiles/classInDept.html', {'dept': dept})
    
def uploads(request, class_id):
    academic_class = get_object_or_404(Academic_class, pk=class_id)
    return render(request, 'wpFiles/uploads.html', {'academic_class': academic_class})
    
def uploadFile(request):
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/wpFiles')
    else:
        form = UploadForm()
    return render(request, 'wpFiles/upload.html', {'form': form})

def search(request):
    criteria = request.GET.get('criteria')
    length = len(watson.search(str(request.GET.get('q'))))
    #if length == 0:
    #    return
    if criteria == 'up':
        search_results = watson.filter(Upload, str(request.GET.get('q')))
        return render(request, 'wpFiles/search.html', {'search_results':search_results}) 
    elif criteria == 'de':   
        search_results = watson.filter(Academic_dept, str(request.GET.get('q')))
        return render(request, 'wpFiles/searchDept.html', {'search_results':search_results}) 
    elif criteria == 'co':
        search_results = watson.filter(Academic_class, str(request.GET.get('q')))
        return render(request, 'wpFiles/searchClass.html', {'search_results':search_results}) 

class signup(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'wpFiles/signup.html'

    
        
   
    
  
           
        

final_proj/mysite/wpFiles/templates/wpFiles/base.html
<!doctype html>

{% load static %}
{% load ratings %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
               <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go" required>
                </form>
             </li>
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <h1 class="col-sm-2 offset-sm-2"> Academic Departments </h1>
    </div>
</div>


<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul>

final_proj/mysite/wpFiles/templates/wpFiles/classInDept.html
<!doctype html>

{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
               <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go" required>
                </form>
             </li>
           {% if user.is_authenticated %}
             <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
           {% else %}
             <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
           {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
    <li class="breadcrumb-item"> {{ dept.dept_code }} </li>
</ul>
        

<h1 class="container">{{ dept.dept_code }}</h1>
<ul class="list-group">
{% for academic_class in dept.academic_class_set.all %}
    <li class="list-group-item">
        <a href="{% url 'uploads' academic_class.pk %}">
            {{ academic_class.class_code }}: {{ academic_class.class_name }}
        </a>
    </li>
{% endfor %}
</ul>

final_proj/mysite/wpFiles/templates/wpFiles/index.html
<!doctype html>

{% load static %}
{% load ratings %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
               <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go" required>
                </form>
             </li>
           {% if user.is_authenticated %}
             <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
           {% else %}
             <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
           {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    <div class="row">
        <h1 class="col-sm-2 offset-sm-2"> Academic Departments </h1>
    </div>
</div>


<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul>

{% if dept_list %}
    <ul class="list-group">
    {% for dept in dept_list %}
        <li class="list-group-item">
            <a href="{% url 'classInDept' dept.id %}">
                {{ dept.dept_code }}: {{ dept.dept_name }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No classes are available.</p>
{% endif %}
</div>

final_proj/mysite/wpFiles/templates/wpFiles/search.html
{% load static %}
{% load ratings %}
<html>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
                <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go" required>
                </form>
            </li>
          {% if user.is_authenticated %}
            <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul> 



{% if search_results %}
  <h1 class="container">
      Search returned {{ search_results|length }} result(s):
  </h1>
  <table class="table">
    <tr>
	    <th>Filename</th><th>Upload Date</th><th>Rating</th>
    </tr>
  {% for result in search_results %} 
      <tr>
        <td><a href="{{ result.document.url }}">{{ result.alias }}</a></td>
        <td>{{ result.upload_date }}</td>
        <td>{% ratings result 15 15 %}</td>
      </tr>
    
  
  {% endfor %}
{% endif %}

final_proj/mysite/wpFiles/templates/wpFiles/searchClass.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
	        <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go">
                </form>
            </li>
          {% if user.is_authenticated %}
            <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul> 



{% if search_results %}
  <h1 class="container">
      Search returned {{ search_results|length }} result(s):
  </h1>
  <table class="table">
    <tr>
	    <th>Course Code</th><th>Course Name</th>
    </tr>
  {% for result in search_results %} 
      <tr>
        <td><a href="{% url 'uploads' result.pk %}">{{ result.class_code }}</a></td>
        <td>{{ result.class_name }}</td>
      </tr>
  {% endfor %}
{% endif %}

final_proj/mysite/wpFiles/templates/wpFiles/searchDept.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
	        <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go">
                </form>
            </li>
          {% if user.is_authenticated %}
            <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul> 



{% if search_results %}
  <h1 class="container">
      Search returned {{ search_results|length }} result(s):
  </h1>
  <table class="table">
    <tr>
	    <th>Department Code</th><th>Department Name</th>
    </tr>
  {% for result in search_results %} 
      <tr>
        <td><a href="{% url 'classInDept' result.id %}">{{ result.dept_code }}</a></td>
        <td>{{ result.dept_name }}</td>
      </tr>
  {% endfor %}
{% endif %}

final_proj/mysite/wpFiles/templates/wpFiles/signup.html
{% load static %}

<html>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
	             <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go">
                </form>
            </li>
          {% if user.is_authenticated %}
            <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
</ul> 

{% block content %}
<div class="container">
  <h1>Create an Account</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>
</div>
{% endblock %}

final_proj/mysite/wpFiles/templates/wpFiles/uploads.html
{% load static %}
{% load ratings %}
<html>
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>



<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<div class="container">
    <div class="jumbotron">
    <h1> WPFiles </h1>
        <p> An online repository for all studying materials.</p>
    </div>
</div>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'index' %}"> Home </a></li>
            <li><a href="{% url 'uploadFile' %}"> Upload File </a></li>
            <li>
                <form class="navbar-form navbar-right" action="{% url 'search' %}">
                  <input name="q" value="{{request.GET.q}}" placeholder="Search" required>
                   <select name="criteria" required>
                    <option value="" disabled selected>Search in...</option>
                    <option value="up">Uploads</option>
                    <option value="de">Departments</option>
                    <option value="co">Courses</option>
                  </select>
                  <input type="submit" value="Go" required>
                </form>
            </li>
          {% if user.is_authenticated %}
            <li class="navbar-left"><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="navbar-left"><a href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
    </div>
</nav>

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
    <li class="breadcrumb-item"><a href="../{{ academic_class.dept_code.pk }}"> 
         {{academic_class.dept_code }}</a> </li>
    <li class="breadcrumb-item"> {{ academic_class.class_code }} </li>
</ul> 


<h1 class="container">
    {{academic_class.class_code}}: {{ academic_class.class_name }}
</h1>
<table class="table">
<tr>
	<th>Filename</th><th>Upload Date</th><th>Rating</th>
</tr>

{% for upload in academic_class.upload_set.all %}
	<tr>    
		<td><a href="{{ upload.document.url }}">{{ upload.alias }}</a></td>
		<td>{{ upload.upload_date }}</td>
		<td>{% ratings upload 15 15 %}</td>
  </tr>
{% endfor %}
</table>

final_proj/mysite/wpFiles/templates/wpFiles/wpFiles/classInDept.html
{% extends 'wpFiles/base.html' %}
{% block content %}

<ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
    <li class="breadcrumb-item"> {{ dept.dept_code }} </li>
</ul>
        

<h1 class="container">{{ dept.dept_code }}</h1>
<ul class="list-group">
{% for academic_class in dept.academic_class_set.all %}
    <li class="list-group-item">
        <a href="{% url 'uploads' academic_class.pk %}">
            {{ academic_class.class_code }}: {{ academic_class.class_name }}
        </a>
    </li>
{% endfor %}
</ul>
{% endblock %}

final_proj/mysite/wpFiles/templates/wpFiles/wpFiles/uploads.html
{% extends 'wpFiles/base.html' %}
{% block content %}

{% load ratings %}
<ul class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'index' %}"> Home </a></li>
  <li class="breadcrumb-item"><a href="../{{ academic_class.dept_code.pk }}"> 
     {{ academic_class.dept_code }}</a> </li>
  <li class="breadcrumb-item"> {{ academic_class.class_code }} </li>
</ul> 


<h1 class="container">
   {{ academic_class.class_code }}: {{ academic_class.class_name }}
</h1>

<table class="table">

<tr>
	<th>Filename</th><th>Upload Date</th><th>Rating</th>
</tr>

{% for upload in academic_class.upload_set.all %}
	<tr>    
		<td><a href="{{ upload.document.url }}">{{ upload.alias }}</a></td>
		<td>{{ upload.upload_date }}</td>
		<td>{% ratings upload 15 15 %}</td>
  </tr>
{% endfor %}

</table>
{% endblock %}